name: random_user_fetcher
description: A Dart console app to fetch random user data
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0